IF NOT EXISTS (SELECT * FROM sys.databases WHERE NAME = N'DB_OLIST')
BEGIN
	CREATE DATABASE DB_OLIST;
END;
GO
USE DB_OLIST;
GO
CREATE SCHEMA RAW;
GO
CREATE SCHEMA STAGING;
GO
CREATE SCHEMA PROCESSING;
GO
CREATE SCHEMA MART;
GO